### ISSUE TITLE
fix: Spotlight on Welcome Tutorial 

### ISSUE THREAD

**Issue by hanlinc27** [uwblueprint/shoe-project#167]
![image.png](https://images.zenhubusercontent.com/5f751c140f9211c62c8f2233/fe93eaef-d34d-4f4f-be28-2ffeb42dbc99)
vs. 
![image.png](https://images.zenhubusercontent.com/5f751c140f9211c62c8f2233/510cacb7-7006-401f-937a-7253aa060b96)

**Comment by nimwijetunga** [comment]
- Spotlight icon 
- Move the box to point to the icon
