### ISSUE TITLE
Do an accessibility audit on the web app

### ISSUE THREAD

**Issue by AbhiPrasad** [uwblueprint/shoe-project#170]
Let's make sure we are doing our best a11y wise.

1) https://reactjs.org/docs/accessibility.html
2) https://www.npmjs.com/package/eslint-plugin-jsx-a11y and https://github.com/dequelabs/axe-core-npm/tree/develop/packages/react for automated testing

**Comment by nimwijetunga** [comment]
@AbhiPrasad what's the status on this? Should we close it since we're close to EOT?

**Comment by AbhiPrasad** [comment]
Yup I can do a quick lighthouse check and give this a look - I've done it before for other sites.

**Comment by AbhiPrasad** [comment]
lol 
![image](https://user-images.githubusercontent.com/18689448/116731739-19641c80-a9b8-11eb-9762-a0a47ff0faf1.png)
