### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#183]
What we need to be mobile friendly:

- filter re-scaled

- Pin preview needs to be re-scaled (flow might also be different)

- Help page needs to re-scaled to fit screen

- Read full story needs re-scaling 

- Re-scale tour to fir screen

- We need origin country for mobile to display on map???? (low priority)

**Comment by hanlinc27** [comment]
- [x] Help Drawer
- [ ] Zoom Controls
- [x] Story Drawer
- [x] Welcome Tutorial
- [ ] Filter
- [ ] Pin Preview
