### ISSUE TITLE
Multimedia

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#185]
- Videos are on Youtube (backend we need a new column in DB for yt link)
  - embed YT on the frontend

- Investigate where to host audio for free (most likely google drive) and get public link
      - Whoever is working on this needs to check if google drive works to host and stream audio, if not whats the alternative
      - embed audio file on the frontend

- Decide whether to continue hosting images on S3 or do it on something like G-Drive (theyll have to host it)
   - Be able to upload an image to S3 from the backend when the image is given by the frontend
   - If it's too much work to upload images from the backend then consider using G-Drive (research)

**Comment by Shehryar21** [comment]
Update: Audio files on GDrive can be used in the frontend

**Comment by s278gupt** [comment]
some questions after doing a lil digging online:

1. Do the multimedia (video, audio, image) columns belong to the `Story` object? And I'm assuming it's one column per link? (I can do a quick pr once this is answered)

>  Be able to upload an image to S3 from the backend when the image is given by the frontend
2. Will this be part of the functionality of an existing post handler, or are we creating a new endpoint specifically for uploading images?
3. There's a couple ways we could go about this. What are your thoughts:
_way 1_:
- frontend uploads image to our server? (where do we store file when we pass it to backend? excuse my ignorance, haven't worked with passing files through api before)
- backend handles the uploading to s3

_way 2_:
- frontend sends `filename` + other fields in request to backend
- backend generates presigned url and sends it as response to frontend
- frontend uses response to request upload to s3

_way 3_:
- entirely frontend 
(i know this is a terrible option, secrets and all, just wanted to be exhaustive in all the options we have)

**Comment by nimwijetunga** [comment]
One thing to note is that we will no longer be doing audio after discussing with the client

1. Yes images and video belong to the story object so we need to add a new column to the model to store a youtube link (video). However we also now have that one story can have multiple images so we need to migrate the database so that the image_url column is now an array (instead of a single value) 

2. No this will be part of the existing story upload endpoint (the user can enter story details as well as pass images)

3. @Shehryar21 is currently looking into doing it using way 1 (essentially we store the image in memory on the backend once we receive it). Ideally we don't want to do way 3 because of security reasons (may expose the s3 bucket). @s278gupt can you look into way 2 and see how easy/hard it is to implement. We will decide (depending on engineering effort) to either go with way 1 or 2 -> One thing to consider for way 2 is how to track which images the user uploaded for a given story (so we can add it to the database)
