### ISSUE TITLE
Banners for map pins w/ filter applied

### ISSUE THREAD

**Issue by jenna-hirji** [uwblueprint/shoe-project#190]
![Screen Shot 2021-01-19 at 9.51.39 PM.png](https://images.zenhubusercontent.com/5f729c0ddd5fa000d671b685/9561f12c-6f7e-4076-af2c-7bdf1bff539c)

https://www.figma.com/file/ga8lgXwbdArh0Mo1iTIfcx/Map-Designs?node-id=152%3A4399

As a user, I want to see which pins correspond to the filter options I have selected, so that I can choose which story I want to preview/read.

Banners will appear when:
- there are two or more filters applied, and
- the user needs to be zoomed into the city enough to see the banners appear - at the point where each story pin appears. When pins are collapsed they won't see the banners

**Comment by nimwijetunga** [comment]
Probably wont get to this so closing
