### ISSUE TITLE
Add Video (Youtube) to stories on the map

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#199]

**Comment by jennahirji** [comment]
https://www.figma.com/file/ga8lgXwbdArh0Mo1iTIfcx/Map-Designs?node-id=422%3A5499
<img width="313" alt="Screen Shot 2021-01-26 at 8 40 38 PM" src="https://user-images.githubusercontent.com/46453023/105929983-c1172a80-6016-11eb-9e4a-fada9435900e.png">
