### ISSUE TITLE
All Stories - Backend

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#226]
- Modify the stories model to have a column which indicates whether the story is visible or not (i.e a boolean) on the map
     - **Note:** This blocks frontend so get a pr done for this ASAP and get it merged (separate from the other tasks in this ticket)
- Create an endpoint that returns all stories in the backend (may be able to just use the current all stories endpoint)
- Modify the all stories endpoint to accept a query parameter: `tags=[tagA, tagB, tagC]`  which gets all the stories that have been tagged with fields in the `tag` array (as long as a story has at least one of the tags in tag array you should return it)
- Modify the all stories endpoint to accept a query parameter: `visibility=[true/false]` which will get stories that are visible or hidden
- Modify the all stories endpoint to accept two query parameters: `sort=[columnA, columnB, ...]&order=[asc,desc,...]` where you return all the stories sorted by the respective columns in the appropriate order. For the example above sort the stories on columnA ascending and columnB descending
   - **Note:** Sorting should be applied after filtering and should be the last step in the endpoint before returning the stories
   - The sort columns are: `story_name, year, author_name, author_country`

**Comment by DinuWije** [comment]
To send arrays as query parameters do the following:
arrayName?=arrayVal1&arrayName=arrayVal2& ... 

Example:
localhost:8900/api/stories?sort=current_city&sort=year&order=asc&order=desc&tags=EDUCATION&tags=REFUGEE
