### ISSUE TITLE
Investigate Optimizing Image Storage in Backblaze

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#268]
- Compressing images in blackblaze
- Cache Images (Redis - In memory cache)
  - What policy
  - How many images to cache
  - When to evict
  - How to use redis with heroku and limitations

**Comment by s278gupt** [comment]
tech design brief: https://docs.google.com/document/d/1ebRTtHBe3gGdTpZ1zmYw4-heIJLfFOZzIs3hKyyKxBM/edit?usp=sharing

**Comment by s278gupt** [comment]
- implemented browser-level caching which ensures that images are downloaded _once_ per user (cache duration = 1 day) 
- implementing file size checks on frontend and backend
   - https://github.com/uwblueprint/shoe-project/issues/278
   - https://github.com/uwblueprint/shoe-project/issues/279
