### ISSUE TITLE
[TEMPLATE] Bug X

### ISSUE THREAD

**Issue by nimwijetunga** [uwblueprint/shoe-project#302]
# Description

Brief description of the bug. If it's a frontend issue attach a screenshot, if it's a backend issue try going to the network tab on chrome and identifying the error that is thrown (attach that as a screenshot here).

# Steps to Reproduce

A list of steps that can help someone to reproduce this bug locally

1. do x
2. do y
3. do z

# Potential Solution

If you know how to fix this bug or know where to look include that here. It could be useful for whoever is picking up the bug

# Notes

Anything else you want to mention

**Comment by liu-jeffrey** [comment]
What a terrifying bug 💀
