### ISSUE TITLE
Style Login Screen as Per Figma

### ISSUE THREAD

**Issue by pamwang** [uwblueprint/shoe-project#311]
# Description
1. Missing Header on Login Screen 
2. The background colour is blue (#F5FBFC), not white. 
3. The box containing the login info needs to be fatter

# Steps to Reproduce
1. Go to Log in Page

# Potential Solution
N/A

# Notes
Here's how it should look
<img width="751" alt="Screen Shot 2021-04-27 at 8 21 36 PM" src="https://user-images.githubusercontent.com/31713921/116328071-2b667500-a796-11eb-99dc-7bae88e81ff3.png">

**Comment by hanlinc27** [comment]
Closed in #344
