### ISSUE TITLE
Can't search by tags

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/shoe-project#312]
# Description

The search bar doesn't search through the tags in the stories. 

# Steps to Reproduce

A list of steps that can help someone to reproduce this bug locally

1. Go to allstories page 
2. Try searching by a tag name (ie. "Education")
3. see that nothing shows up 

![image.png](https://images.zenhubusercontent.com/5f751c1e3db0817be14e4a9e/de9fa59b-22ce-4acb-b15b-f12607c1d536)

# Notes

Seems kinda tough to implement because you'd have to search through individual arrays for tags

**Comment by hanlinc27** [comment]
Tags should be filtered not searched
