### ISSUE TITLE
Adding Tags in Upload/Edit story lack design prompts

### ISSUE THREAD

**Issue by liu-jeffrey** [uwblueprint/shoe-project#321]
From our current implementation we have this:
![image](https://user-images.githubusercontent.com/35406352/116330242-16d8ab80-a79b-11eb-9961-18b4bee621ce.png)

This is our Figma design:
![image](https://user-images.githubusercontent.com/35406352/116330342-4edfee80-a79b-11eb-8d3f-dc7642befb77.png)

As a new user, idk how to add my own tags until I've played around.

**Comment by DinuWije** [comment]
Functionality is there, but meeting design requirements is out of scope
