### ISSUE TITLE
Cannot add tags with a space in it

### ISSUE THREAD

**Issue by Shehryar21** [uwblueprint/shoe-project#323]
Cannot add a tag with a space.

![image](https://user-images.githubusercontent.com/37384882/116332228-5bfedc80-a79f-11eb-8d36-64ea2c8c15ee.png)

# Steps to Reproduce

1. When you press space, the tag automatically gets added, which is why cannot have a tag with a space

# Potential Solution

Not sure, ig just need to prevent tag being added when pressed space

**Comment by nimwijetunga** [comment]
duplicate
