### ISSUE TITLE
Preview button on Upload Story Page is not Working when invalid Youtube link is entered

### ISSUE THREAD

**Issue by pamwang** [uwblueprint/shoe-project#352]
# Description
The preview button is not working. After filling out all the fields in the upload story form, then pressing "Preview Story" I am getting a blank page. See below:
<img width="1440" alt="Screen Shot 2021-05-01 at 2 22 05 PM" src="https://user-images.githubusercontent.com/31713921/116791469-9c54a800-aa88-11eb-980c-a896624b9e52.png">

# Steps to Reproduce
1. Upload A Story
2. Fill out all of the fields (including video link)
3. Click Preview Story

Result: Blank Screen
Expected Result: Preview Story Page

**Comment by hanlinc27** [comment]
Closed in #353
