### ISSUE TITLE
Delete Story Button needs to be Red

### ISSUE THREAD

**Issue by pamwang** [uwblueprint/shoe-project#357]
# Description
The delete story needs to be red. 
<img width="1440" alt="Screen Shot 2021-05-01 at 2 45 21 PM" src="https://user-images.githubusercontent.com/31713921/116793046-5dc3eb00-aa92-11eb-91fd-8d9a1745ee8a.png">

# Steps to Reproduce
1. Click on a story name
2. Click Edit

Result: Blue Delete button
Expected Result: Red Delete Button

**Comment by nimwijetunga** [comment]
#363 closes this
