### ISSUE TITLE
[Investigate] How to calculate pin position based on city name

### ISSUE THREAD

**Issue by dhillondeep** [uwblueprint/shoe-project#52]

**Comment by aspensantos** [comment]
I tested forward geocoding using the MapBox API, here are the corresponding request and response:

`curl "https://api.mapbox.com/geocoding/v5/mapbox.places/toronto.json?limit=1&country=CA&access_token=MAPBOX_ACCESS_TOKEN_HERE"`

```
{
	"type": "FeatureCollection",
	"query": ["toronto"],
	"features": [{
		"id": "place.1521272661948910",
		"type": "Feature",
		"place_type": ["place"],
		"relevance": 1,
		"properties": {
			"wikidata": "Q172"
		},
		"text": "Toronto",
		"place_name": "Toronto, Ontario, Canada",
		"bbox": [-79.639302406235, 43.5603428815601, -79.1134670108977, 43.8554654957061],
		"center": [-79.3849, 43.6529],
		"geometry": {
			"type": "Point",
			"coordinates": [-79.3849, 43.6529]
		},
		"context": [{
			"id": "region.10598799396263190",
			"wikidata": "Q1904",
			"short_code": "CA-ON",
			"text": "Ontario"
		}, {
			"id": "country.10278600750587150",
			"wikidata": "Q16",
			"short_code": "ca",
			"text": "Canada"
		}]
	}],
	"attribution": "NOTICE: © 2020 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
}
```

We can use the value of center in this response for our latitude and longitude, I made this request by following this documentation:
https://docs.mapbox.com/api/search/

And there is an early stage MapBox API wrapper for golang which includes the forward geocoding we need, so we can make a call to the MapBox API when we create a story with the city name, and then store the latitude and longitude we got in the DB.
Here is the golang wrapper:
https://github.com/ryankurte/go-mapbox
