### ISSUE TITLE
Create Edge Markers to point towards nearest story

### ISSUE THREAD

**Issue by dhillondeep** [uwblueprint/shoe-project#90]
A user should see arrows when no markers are in sight

![Screen Shot 2020-11-25 at 9.02.32 PM.png](https://images.zenhubusercontent.com/59e40dfeb0222d5de47bbe0d/88ef9305-538a-4eed-a4da-da6ce4358a70)

**Comment by hanlinc27** [comment]
General Idea: https://ubergesundheit.github.io/Leaflet.EdgeMarker/ Should probably implement after clustering
